Sample for division

In [1]:
18/4

4.5

example for taking the floor 

In [2]:
18 // 4

4

example for multiplying 

In [4]:
5 * 5

25

example for power

In [5]:
5**3

125

example for strings

In [6]:
string = 'string'

example for multiplying strings

In [9]:
string*5

'stringstringstringstringstring'

example for array 

In [12]:
arr = [i for i in range(1,20,5) ]

In [13]:
arr

[1, 6, 11, 16]

example for accessing the array indicies

In [14]:
arr [1:3]

[6, 11]

example for the size of the array 

In [15]:
len(arr)

4

example for concat

In [16]:
arr2 = [i for i in range(20,100,5)]

In [17]:
arr2

[20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [18]:
arr3 = arr + arr2

In [19]:
arr3

[1, 6, 11, 16, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [20]:
arr

[1, 6, 11, 16]

In [22]:
arr2 

[20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

the example of working with a string

In [23]:
print("we want to print number %d"%(2))

we want to print number 2


In [24]:
print("we want to print number "+str(2))

we want to print number 2


example of working with functions

In [28]:
def func (a=1,b=1):
    return a/b


In [29]:
print(func(2,3))

0.6666666666666666


In [30]:
print(2)

2


In [31]:
print(func(2,1))

2.0


In [33]:
print(func(b=2,a=1))

0.5


In [35]:
def listGetter(*list1):
    for i in list1:
        print(i)

In [38]:
listGetter([10,20,30],[40,50])

[10, 20, 30]
[40, 50]


some examples for getting an input

In [45]:
a = str(input(prompt='please enter : '))

please enter : 2


In [46]:
a

'2'

some examples for importing library 

In [47]:
import numpy as np
from numpy import random as rand

for this part we will use the example of using numpy arrays

In [54]:
arr = np.array([i for i in range(1,20)],dtype=np.int32)

In [55]:
arr.shape

(19,)

In [56]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [57]:
arr = arr.reshape(19,1)

In [58]:
print(arr)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [59]:
ind = np.arange(10,20,2)

In [60]:
ind

array([10, 12, 14, 16, 18])

In [61]:
rand.shuffle(ind)

In [62]:
ind

array([14, 10, 12, 16, 18])

In [63]:
np.random.shuffle(ind)

In [64]:
ind

array([18, 14, 16, 12, 10])

In [65]:
zeros32 = np.zeros(shape=[3,2])

In [66]:
ones32 = np.ones(shape=[3,2])

In [67]:
con = np.concatenate([zeros32,ones32])

In [68]:
con.shape

(6, 2)

In [69]:
con

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [70]:
con = np.concatenate([zeros32,ones32],axis=1)

In [71]:
con.shape

(3, 4)

In [72]:
con

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [74]:
zeros32 += 4

In [75]:
ones32 *= 6

In [76]:
zeros32

array([[4., 4.],
       [4., 4.],
       [4., 4.]])

In [77]:
ones32

array([[6., 6.],
       [6., 6.],
       [6., 6.]])

In [78]:
res = ones32 - zeros32

In [79]:
res

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [80]:
sel = np.ones(shape=[2,3])*5

In [81]:
sel

array([[5., 5., 5.],
       [5., 5., 5.]])

In [82]:
out = np.dot(zeros32,sel)

In [85]:
print(zeros32.shape)
print(sel.shape)
print(out.shape)

(3, 2)
(2, 3)
(3, 3)


In [86]:
out

array([[40., 40., 40.],
       [40., 40., 40.],
       [40., 40., 40.]])

In [87]:
import numpy as np
arr = np.arange(0,10)

In [88]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [89]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [90]:
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
arr / arr

d:\users\pooria\anaconda3\envs\myonlyenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [92]:
1 / arr

d:\users\pooria\anaconda3\envs\myonlyenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [93]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [94]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [95]:
np.max(arr)

9

In [106]:
np.random.seed(1)
np.random.shuffle(arr)
print(arr.argmax())
print(arr[arr.argmax()])

7
9


In [108]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [109]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [111]:
np.random.seed(1)
np.random.randn(5,5)

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595]])

In [112]:
ranarr = np.random.randint(0,50,10)

In [113]:
ranarr

array([26, 25, 40, 22,  9,  3, 39, 23, 36, 27])

In [115]:
ranarr[2:4]=20

In [117]:
ranarr

array([26, 25, 20, 20,  9,  3, 39, 23, 36, 27])

In [119]:
ranarr[[2,4,6,8]]

array([20,  9, 39, 36])

In [120]:
arr[arr>2]

array([8, 5, 3, 4, 7, 6, 9])

now we will spend time on scipy

In [102]:
import scipy
from scipy import linalg

In [105]:
# Determinant
A = np.array([[1,2,3],[4,5,6],[7,8,8]])
print(linalg.det(A))

3.0


now we will see pandas and its Series

In [121]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array(my_list)
d = {'a':10,'b':20,'c':30}

In [122]:
import pandas as pd

In [123]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [124]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [125]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [126]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [127]:
# this is to demonstrate that series can be of any data type

In [128]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [129]:
# I mean anyyy Thing :))

In [130]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [131]:
a = pd.Series(data=my_list,index=labels)

In [133]:
b = pd.Series(data=[1,2],index=['a','b'])

In [134]:
a + b

a    11.0
b    22.0
c     NaN
dtype: float64

from here its about panda Data frames

In [138]:
np.random.seed(1)
df = pd.DataFrame(np.random.randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [141]:
df.head(3)

W         X         Y         Z
A  1.624345 -0.611756 -0.528172 -1.072969
B  0.865408 -2.301539  1.744812 -0.761207
C  0.319039 -0.249370  1.462108 -2.060141

In [142]:
df

W         X         Y         Z
A  1.624345 -0.611756 -0.528172 -1.072969
B  0.865408 -2.301539  1.744812 -0.761207
C  0.319039 -0.249370  1.462108 -2.060141
D -0.322417 -0.384054  1.133769 -1.099891
E -0.172428 -0.877858  0.042214  0.582815

In [143]:
df['W']

A    1.624345
B    0.865408
C    0.319039
D   -0.322417
E   -0.172428
Name: W, dtype: float64

In [144]:
df[['W','Z']]

W         Z
A  1.624345 -1.072969
B  0.865408 -0.761207
C  0.319039 -2.060141
D -0.322417 -1.099891
E -0.172428  0.582815

In [146]:
# sql format :D
df.W

A    1.624345
B    0.865408
C    0.319039
D   -0.322417
E   -0.172428
Name: W, dtype: float64

In [147]:
type(df['W'])

pandas.core.series.Series

In [148]:
df['new'] = df['W'] + df['Y']

In [149]:
df.head(3)

W         X         Y         Z       new
A  1.624345 -0.611756 -0.528172 -1.072969  1.096174
B  0.865408 -2.301539  1.744812 -0.761207  2.610219
C  0.319039 -0.249370  1.462108 -2.060141  1.781147

In [150]:
df.drop('new',axis=+1)

W         X         Y         Z
A  1.624345 -0.611756 -0.528172 -1.072969
B  0.865408 -2.301539  1.744812 -0.761207
C  0.319039 -0.249370  1.462108 -2.060141
D -0.322417 -0.384054  1.133769 -1.099891
E -0.172428 -0.877858  0.042214  0.582815

In [152]:
# and its still here :D
df

W         X         Y         Z       new
A  1.624345 -0.611756 -0.528172 -1.072969  1.096174
B  0.865408 -2.301539  1.744812 -0.761207  2.610219
C  0.319039 -0.249370  1.462108 -2.060141  1.781147
D -0.322417 -0.384054  1.133769 -1.099891  0.811352
E -0.172428 -0.877858  0.042214  0.582815 -0.130214

In [153]:
df.drop('E',axis=0)

W         X         Y         Z       new
A  1.624345 -0.611756 -0.528172 -1.072969  1.096174
B  0.865408 -2.301539  1.744812 -0.761207  2.610219
C  0.319039 -0.249370  1.462108 -2.060141  1.781147
D -0.322417 -0.384054  1.133769 -1.099891  0.811352

In [154]:
df.loc['A']

W      1.624345
X     -0.611756
Y     -0.528172
Z     -1.072969
new    1.096174
Name: A, dtype: float64

In [155]:
df.loc[['A','B'],['W','Y']]

W         Y
A  1.624345 -0.528172
B  0.865408  1.744812

In [156]:
df

W         X         Y         Z       new
A  1.624345 -0.611756 -0.528172 -1.072969  1.096174
B  0.865408 -2.301539  1.744812 -0.761207  2.610219
C  0.319039 -0.249370  1.462108 -2.060141  1.781147
D -0.322417 -0.384054  1.133769 -1.099891  0.811352
E -0.172428 -0.877858  0.042214  0.582815 -0.130214

In [157]:
df > 0

W      X      Y      Z    new
A   True  False  False  False   True
B   True  False   True  False   True
C   True  False   True  False   True
D  False  False   True  False   True
E  False  False   True   True  False

In [158]:
df[df > 0]

W   X         Y         Z       new
A  1.624345 NaN       NaN       NaN  1.096174
B  0.865408 NaN  1.744812       NaN  2.610219
C  0.319039 NaN  1.462108       NaN  1.781147
D       NaN NaN  1.133769       NaN  0.811352
E       NaN NaN  0.042214  0.582815       NaN

In [159]:
df[df['W']>0]

W         X         Y         Z       new
A  1.624345 -0.611756 -0.528172 -1.072969  1.096174
B  0.865408 -2.301539  1.744812 -0.761207  2.610219
C  0.319039 -0.249370  1.462108 -2.060141  1.781147

In [160]:
df[df['W']>0]['Y']

A   -0.528172
B    1.744812
C    1.462108
Name: Y, dtype: float64

In [162]:
df[(df['W']>0) & (df['Y'] > 1)]

W         X         Y         Z       new
B  0.865408 -2.301539  1.744812 -0.761207  2.610219
C  0.319039 -0.249370  1.462108 -2.060141  1.781147

In [163]:
df.reset_index()

index         W         X         Y         Z       new
0     A  1.624345 -0.611756 -0.528172 -1.072969  1.096174
1     B  0.865408 -2.301539  1.744812 -0.761207  2.610219
2     C  0.319039 -0.249370  1.462108 -2.060141  1.781147
3     D -0.322417 -0.384054  1.133769 -1.099891  0.811352
4     E -0.172428 -0.877858  0.042214  0.582815 -0.130214

In [165]:
df.reset_index().drop('index',axis=1).set_index(df.reset_index()['index'])

W         X         Y         Z       new
index                                                  
A      1.624345 -0.611756 -0.528172 -1.072969  1.096174
B      0.865408 -2.301539  1.744812 -0.761207  2.610219
C      0.319039 -0.249370  1.462108 -2.060141  1.781147
D     -0.322417 -0.384054  1.133769 -1.099891  0.811352
E     -0.172428 -0.877858  0.042214  0.582815 -0.130214

In [195]:
# from here on out this won't come in handy , for your owm study :D
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
ziped = zip(outside,inside)

In [196]:
ziped

In [197]:
listed = list(ziped)

In [198]:
listed

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [199]:
hier_index = pd.MultiIndex.from_tuples(listed)

In [200]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [201]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])

In [202]:
df

A         B
G1 1  0.300170 -0.352250
   2 -1.142518 -0.349343
   3 -0.208894  0.586623
G2 1  0.838983  0.931102
   2  0.285587  0.885141
   3 -0.754398  1.252868

In [203]:
df.loc['G1']

A         B
1  0.300170 -0.352250
2 -1.142518 -0.349343
3 -0.208894  0.586623

In [204]:
df.loc['G1'].loc[1]

A    0.30017
B   -0.35225
Name: 1, dtype: float64